//
//  FinixDelegate.swift
//  FinixPOS
//
//  Created by Jack Tihon on 3/31/20.
//  Copyright © 2020 Finix Payments, Inc. All rights reserved.
//

import Foundation

/// Card reader status change monitoring.
/// Conforming delegates will receive card reader status changes including connection, disconnection, errors, and low battery.
public protocol FinixDelegate: AnyObject {

    /// <#Description#>
    /// - Parameter deviceInfo: <#deviceInfo description#>
    func didDiscoverDevice(_ deviceInfo: DeviceInfo)

    /// <#Description#>
    /// - Parameter deviceInfo: <#deviceInfo description#>
    func deviceDidConnect(_ deviceInfo: DeviceInfo)

    /// On device disconnection complete.
    func deviceDidDisconnect()

    /// On reader error.
    /// - Parameter error: error generated by the device
    func deviceDidError(_ error: Error)
}
